{{ range $key, $app := .Values.applications }}
{{if not (eq $app.disabled true )}}
{{ if eq $app.appType "listener" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.projectName }}-{{ $app.name }}-rr-listener
data:
  rr.yaml: |
    version: '3.8'
    server:
      command: "php /var/www/php/vendor/bin/rr-worker start"
      relay: "pipes"
    rpc:
      listen: tcp://0.0.0.0:6001
    service:
      listener-{{ $app.listenerSettings.driver}}-{{ $app.listenerSettings.channel }}:
        service_name_in_log: true
        timeout_stop_sec: 5
        remain_after_exit: true
        process_num: {{ $app.listenerSettings.workerCount | default 1}}
        restart_sec: 1
        command: "php /var/www/php artisan frock:{{ $app.listenerSettings.driver}}-consumer --messageLimit={{$app.listenerSettings.workerCount | default 1 }}"
---
{{ end }}
{{ end }}
{{ end }}