{{ range $key, $app := .Values.applications }}
{{if not (eq $app.disabled true )}}
{{ if eq $app.appType "http" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.projectName }}-{{ $app.name }}-rr-http
data:
  rr.yaml: |
    version: '3.8'
    logs:
      mode: development
    metrics:
      address: 0.0.0.0:2112
    server:
      command: "php /var/www/php/artisan frock:http-consumer"
      env:
        - XDEBUG_SESSION: 1
      relay: "pipes"
    rpc:
      listen: tcp://0.0.0.0:6001
    {{ if $app.natsAddress }}
    nats:
      addr: {{ $app.natsAddress | quote }}
    {{ end }}
    http:
      address: 0.0.0.0:8080
      internal_error_code: 505
      access_logs: false
      max_request_size: 0
      middleware: [ "headers", "gzip", "static" ]
      pool:
        debug: {{ $.Values.rrDebugMode | default false }}
        num_workers: {{ $app.workersPerPod | default 1 }}
        max_jobs: 32
      static:
        dir: /var/www/php/public
        forbid: [ ".php", ".htaccess" ]
        allow: [ ".js", ".css" ]
        fallback_index: index.php
---
{{ end }}
{{ end }}
{{ end }}