{{ range $key, $app := .Values.applications }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $app.name }}-rr-{{ $app.serviceType }}
data:
  rr.yaml: |
    version: '3.8'
    rpc:
      listen: tcp://0.0.0.0:6001
    {{ if eq $app.serviceType "http" }}
    http:
      address: 0.0.0.0:8080
      internal_error_code: 505
      access_logs: false
      max_request_size: 0
      middleware: [ "headers", "gzip" ]
      pool:
        debug: false
        command: "php my-super-app.php"
    {{ end }}
{{ end }}
