{{ range $appIndex, $application := .Values.applications }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if eq $application.appType "grpc" }}
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- end }}
  name: {{$application.name}}-{{ $.Values.projectName }}-ingress
spec:
  ingressClassName: {{ $.Values.ingressClassName | default "nginx" }}
  rules:
  {{ range $index, $entrypoint := $application.entrypoints}}
    - host: {{ $entrypoint.hostname }}
      http:
        paths:
          {{ range $entrypoint.paths }}
          - path: /
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $application.name }}-{{ $.Values.projectName }}-svc
                port:
                  {{ if eq $application.appType "http"}}
                  number: 8080
                  {{ else if eq $application.appType "grpc"}}
                  number: 9009
                  {{ end}}
          {{ end}}
  {{ end}}
---
{{ end}}
