{{ range $appIndex, $app := .Values.applications }}
{{ if or (eq $app.appType "http") (eq $app.appType "grpc") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ range $annotationKey, $annotation := $app.commonIngressAnnotations }}
    {{ $annotation.name | quote }}: {{ $annotation.value | quote }}
    {{end}}
    {{- if eq $app.appType "grpc" }}
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- end }}
  name: {{$app.name}}-{{ $.Values.projectName }}-ingress
spec:
  ingressClassName: {{ $.Values.ingressClassName | default "nginx" }}
  rules:
  {{ range $index, $entrypoint := $app.entrypoints}}
    - host: {{ $entrypoint.hostname }}
      http:
        paths:
          {{ range $entrypoint.paths }}
          - path: /
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $app.name }}-{{ $.Values.projectName }}-svc
                port:
                  {{ if eq $app.appType "http"}}
                  number: 8080
                  {{ else if eq $app.appType "grpc"}}
                  number: 9009
                  {{ end}}
          {{ end}}
  {{ end}}
---
{{end}}
{{ end}}
