{{ range $key, $app := .Values.applications }}
{{ if or (eq $app.appType "http") (eq $app.appType "grpc") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}-{{ $.Values.projectName }}-svc
spec:
  selector:
    app: {{ $app.name }}-{{ $.Values.projectName }}
  {{ if eq $app.appType "http" }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"
      name: port-8080
  {{ end }}
---
{{ end }}
{{ end }}